name: Check Ignored Items

on:
  push:
    branches:
      - main # Adjust the branch as needed
  schedule:
    - cron: "00 13 * * 5" # 1:00 PM UTC every Friday

jobs:
  Check:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.login == github.actor # Only run on the owner's repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find Ignored Items
        id: find_ignored
        run: |
          ignored=$(find . -type f -name '**' -not -name '*.yml' -exec grep -Hn -e '@phpstan-ignore' -e 'Temporary ignored' -e 'temporary ignored' {} \; || true)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "ignored<<$EOF" >> $GITHUB_ENV
          echo "$ignored" >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Discord Webhook Action
        if: ${{ env.ignored != '' }}
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: |
            ### Checked out code:
            ```php
            ${{ env.ignored }}
            ```
