name: Check TODOs

on:
  push:
    branches:
      - main # Adjust the branch as needed
  schedule:
    - cron: "00 13 * * *" # 1:00 PM UTC everyday

jobs:
  Check:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.login == github.actor # Only run on the owner's repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find TODOs
        id: find_todos
        run: |
          todos=$(find . -type d \( -name .git -o -name .github \) -prune -o -type f -exec grep -Hn -e 'TODO' -e 'todo' -e 'Todo' {} \; || true)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "todos<<$EOF" >> $GITHUB_ENV
          echo "$todos" >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Discord Webhook Action
        if: ${{ env.todos != '' }}
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: |
            ### TODO LIST FOUND:
            ```php
            ${{ env.todos }}
            ```
